// data.js -- que du contenu, zero logique.
// STRINGS/SUCCESS_MSGS/FAIL_MSGS : tous les textes (en/fr).
// LEVELS : les 10 niveaux, chaque exo a name/title/style/html/fnFile/
// stub(toujours vide)/mainCode(lecture seule ou null).

const STRINGS = {
  // -- ecran select --
  select_eyebrow: {en:"Exam Sim · Go Piscine", fr:"Simu Exam · Piscine Go"},
  select_sub: {en:"59 real exercises, N1 to N10 — pulled straight from the real exam pool. Practice mode: pick a level, browse freely. True Exam mode: one random exercise per level, in order, no going back — just like the real thing.",
               fr:"59 vrais exercices, N1 à N10 — tirés direct du vrai pool d'exam. Mode Practice : tu choisis un niveau, tu navigues librement. Mode True Exam : un exo random par niveau, dans l'ordre, sans retour en arrière — comme le vrai."},
  mode_practice: {en:"🎯 Practice", fr:"🎯 Practice"},
  mode_trueexam: {en:"⏱ True Exam", fr:"⏱ True Exam"},
  cat_piscine: {en:"Piscine 01", fr:"Piscine 01"},
  cat_cursus: {en:"Cursus 01", fr:"Cursus 01"},
  cursus_note: {en:"Same 59 exercises as the piscine — you're past that stage, but the exam pool doesn't change, just how it's tracked administratively.",
                fr:"Mêmes 59 exercices que la piscine — t'es déjà dans le cursus, mais le pool d'exam change pas, juste le suivi administratif est différent."},

  // -- ecran rules (avant de demarrer un run) --
  rules_practice_1: {en:"Random draw of exercises from this level's pool — not always the same ones.",
                      fr:"Tirage random d'exercices dans le pool de ce niveau — pas toujours les mêmes."},
  rules_editor_fn: {en:"On the right: your file — completely blank, just like the real exam. You write everything yourself: package declaration, imports, signature, logic. If the exercise expects a function, main.go is shown too (read-only) so you know exactly how it'll be called.",
                     fr:"À droite : ton fichier — complètement vide, comme en vrai exam. Tu écris tout toi-même : déclaration du package, imports, signature, logique. Si l'exercice attend une fonction, main.go est affiché aussi (lecture seule) pour que tu saches exactement comment elle sera appelée."},
  rules_run: {en:'"Run" to test your code in the console below.', fr:'"Run" pour tester ton code dans la console en dessous.'},
  rules_honesty: {en:"The console shows real compiler-style output — same as a real terminal, it won't hold your hand or pinpoint the exact issue for you.",
                  fr:"La console affiche une sortie façon vrai compilateur — comme un vrai terminal, ça te tient pas la main et ça te dit pas précisément le souci."},
  rules_timer: {en:"Time limit, keeps running even if you switch exercises.", fr:"Temps limité, continue même si tu changes d'exercice."},
  rules_cta: {en:"Start", fr:"C'est parti"},
  rules_note: {en:"⚠️ The console is an AI-simulated Go compiler — not a real one running in your browser. Very reliable, but it only works from inside Claude.ai (or your own local server with your own key — ask if you want that set up again).",
               fr:"⚠️ La console est un compilo Go simulé par IA — pas un vrai compilo dans le navigateur. Très fiable, mais ça marche que depuis Claude.ai (ou ton propre serveur local avec ta clé — dis-moi si tu veux qu'on remette ça en place)."},
  change_level: {en:"← change level", fr:"← changer de niveau"},

  // -- ecran exam : editeur + console --
  compiling: {en:"Running...", fr:"Exécution..."},
  term_placeholder: {en:"$ go run .\n(nothing yet — click Run)", fr:"$ go run .\n(rien pour l'instant — clique sur Run)"},
  run_btn: {en:"▶ Run", fr:"▶ Run"},
  submit_btn: {en:"Submit", fr:"Submit"},
  status_succeeded: {en:"SUCCEEDED", fr:"SUCCEEDED"},
  status_failed: {en:"FAILED", fr:"FAILED"},
  clear_btn: {en:"clear", fr:"effacer"},
  prev_btn: {en:"← Previous", fr:"← Précédent"},
  next_btn: {en:"Next →", fr:"Suivant →"},
  finish_now: {en:"Finish now", fr:"Terminer maintenant"},
  no_main: {en:"This exercise is a full standalone program — you write everything in main.go, there's no separate function file.",
            fr:"Cet exercice est un programme autonome complet — tu écris tout dans main.go, y'a pas de fichier fonction séparé."},
  empty_output: {en:"(empty output)", fr:"(sortie vide)"},
  cors_error: {en:"🔌 Run calls the Claude API, which only works from inside Claude.ai. On your own PC without a local relay server, the browser blocks it (CORS) — that's expected. Ask me to set up the local server again if you want this working outside Claude.ai.",
               fr:"🔌 Run appelle l'API Claude, qui marche que depuis Claude.ai. Sur ton PC sans serveur relais local, le navigateur bloque ça (CORS) — c'est normal. Demande-moi de remettre en place le serveur local si tu veux que ça marche en dehors de Claude.ai."},

  // -- mode True Exam --
  te_restart: {en:"restart", fr:"restart"},
  te_next: {en:"next", fr:"next"},
  te_status: {en:"Exo", fr:"Exo"},
  te_title: {en:"True Exam", fr:"True Exam"},

  // -- ecran end --
  end_title: {en:"Session complete", fr:"Session terminée"},
  end_cta_practice: {en:"Draw new exercises, same level 🔁", fr:"Retirer d'autres exos, même niveau 🔁"},
  end_ghost: {en:"← pick another level", fr:"← choisir un autre niveau"},
};

// Terminal flavor messages. FAIL messages are grouped by the kind of
// compiler/runtime error detected, each with a subtle metaphor that
// (very quietly) nods at the actual category of mistake -- never
// spelled out, never exercise-specific, just a faint echo if you
// think about it.
const FAIL_MSGS = {
  missing_return: {
    en:["Your function walked off stage before the final bow. 🎭",
        "The story's missing its last page.",
        "Almost there — but nobody said the last word."],
    fr:["Ta fonction est sortie de scène avant le salut final. 🎭",
        "L'histoire n'a pas de dernière page.",
        "Presque bon — mais personne n'a dit le dernier mot."]
  },
  undefined: {
    en:["Something in there was never properly introduced. 👋",
        "You're calling a name nobody answered to."],
    fr:["Un truc là-dedans n'a jamais été présenté correctement. 👋",
        "Tu appelles un nom que personne n'a repris."]
  },
  unused: {
    en:["You invited someone and never gave them the mic. 🎤",
        "A guest who never got to speak."],
    fr:["T'as invité quelqu'un et jamais donné le micro. 🎤",
        "Un invité qui n'a jamais pu parler."]
  },
  syntax: {
    en:["A door was left wide open somewhere in there. 🚪",
        "One of your brackets is still waiting for its other half."],
    fr:["Une porte est restée grande ouverte quelque part. 🚪",
        "Une de tes accolades attend encore sa moitié."]
  },
  type_mismatch: {
    en:["You tried to fit a square peg where a round one lives. 🔷",
        "Two shapes that were never meant to stack."],
    fr:["T'as essayé de faire rentrer un carré dans un rond. 🔷",
        "Deux formes qui n'étaient pas faites pour s'empiler."]
  },
  generic: {
    en:["The compiler has some things to tell you. Many things.",
        "It blew up, but in a good way (figuratively speaking).",
        "RIP this run. There'll be others.",
        "Error detected. Somewhere, an engineer sighs."],
    fr:["Le compilo a des trucs à te dire. Beaucoup de trucs.",
        "Ça a explosé, mais dans le bon sens du terme.",
        "RIP ce run. Y en aura d'autres.",
        "Erreur détectée. Quelque part, un ingénieur soupire."]
  }
};

const SUCCESS_MSGS = {
  en:["It compiles. Somewhere, an intern is crying tears of joy. 🥲",
      "It runs. Now go check the output actually matches 👁️",
      "No errors. Suspicious. But let's call it a good sign 👀",
      "Zero crashes. The garbage collector is slacking off today."],
  fr:["Ça compile. Quelque part, un stagiaire pleure de joie. 🥲",
      "Ça tourne. À toi de vérifier que le résultat colle vraiment 👁️",
      "Aucune erreur. Suspect. Mais on va dire que c'est bon signe 👀",
      "Zéro crash. Le garbage collector chôme aujourd'hui."]
};

// ============================================================
// data.js -- toutes les donnees : les 59 vrais exercices de la
// piscine Go (N1 a N10), verifies contre le vrai pool d'exam.
//
// `stub` est TOUJOURS vide -- comme en vrai exam. `mainCode` =
// version Cursus (fmt permis). `piscineMain`, quand present,
// = version minimale a la main avec z01.PrintRune (booleen =
// 'T'/'F', string = boucle simple, int = fonction recursive)
// -- verifiee en executant du vrai code Go, pas juste supposee.
// ============================================================

const LEVELS = [
  // --- N1 : Premiers pas ---
  {
    id:'n1', name:'N1',
    topic:"Premiers pas",
    tagline:"First contact — one character, zero mistakes allowed.",
    exercises:[
      {
        name:"onlyz",
        title:"onlyz",
        style:"program",
        html:"<h2>onlyz</h2>\n<h3>Instructions</h3>\n<p>Write a program that displays a <code>z</code> character on the standard output. (and nothing else)</p>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"onlya",
        title:"onlya",
        style:"program",
        html:"<h2>onlya</h2>\n<h3>Instructions</h3>\n<p>Write a program that displays a <code>a</code> character on the standard output. (and nothing else)</p>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"onlyb",
        title:"onlyb",
        style:"program",
        html:"<h2>onlyb</h2>\n<h3>Instructions</h3>\n<p>Write a program that displays a <code>B</code> character on the standard output and nothing else.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run .\nB\n$ go run . &quot;a&quot; &quot;b&quot;\nB\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"onlyf",
        title:"onlyf",
        style:"program",
        html:"<h2>onlyf</h2>\n<h3>Instructions</h3>\n<p>Write a program that displays an <code>f</code> character on the standard output and nothing else.</p>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
  // --- N2 : Boucles & conditions ---
  {
    id:'n2', name:'N2',
    topic:"Boucles & conditions",
    tagline:"If, else, and a whole lot of loops.",
    exercises:[
      {
        name:"rectperimeter",
        title:"rectperimeter",
        style:"function",
        html:"<h2>rectperimeter</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes two <code>int</code>'s as arguments, representing the length of width and height of a rectangle and returning the perimeter of the rectangle.</p>\n<ul>\n<li>If one of the arguments is negative it should return <code>-1</code>.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func RectPerimeter(w, h int) int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(RectPerimeter(10, 2))\n    fmt.Println(RectPerimeter(10, -2))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n24\n-1\n$\n</code></pre>",
        fnFile:"rectperimeter.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.RectPerimeter(10, 2))\n\tfmt.Println(piscine.RectPerimeter(10, -2))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.RectPerimeter(10, 2))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.RectPerimeter(10, -2))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"countcharacter",
        title:"countcharacter",
        style:"function",
        html:"<h2>count-character</h2>\n<h3>Instructions</h3>\n<p>write a function that takes a string and a character as arguments and returns the number of times the character appears in the string.</p>\n<ul>\n<li>if the character is not in the string return 0</li>\n<li>if the string is empty return 0</li>\n</ul>\n<h3>Expected Function</h3>\n<pre><code class=\"language-go\">func CountChar(str string, c rune) int {\n    ...\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(CountChar(&quot;Hello World&quot;, 'l'))\n    fmt.Println(CountChar(&quot;5  balloons&quot;, 5))\n    fmt.Println(CountChar(&quot;   &quot;, ' '))\n    fmt.Println(CountChar(&quot;The 7 deadly sins&quot;, '7'))\n}\n\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\n3\n0\n3\n1\n</code></pre>",
        fnFile:"countcharacter.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.CountChar(\"Hello World\", 'l'))\n\tfmt.Println(piscine.CountChar(\"5  balloons\", 5))\n\tfmt.Println(piscine.CountChar(\"   \", ' '))\n\tfmt.Println(piscine.CountChar(\"The 7 deadly sins\", '7'))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.CountChar(\"Hello World\", 'l'))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.CountChar(\"5  balloons\", 5))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.CountChar(\"   \", ' '))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.CountChar(\"The 7 deadly sins\", '7'))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"checknumber",
        title:"checknumber",
        style:"function",
        html:"<h2>checknumber</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes a <code>string</code> as an argument and returns <code>true</code> if the string contains any number, otherwise return <code>false</code>.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func CheckNumber(arg string) bool {\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(CheckNumber(&quot;Hello&quot;))\n    fmt.Println(CheckNumber(&quot;Hello1&quot;))\n}\n\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\nfalse\ntrue\n$\n</code></pre>",
        fnFile:"checknumber.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.CheckNumber(\"Hello\"))\n\tfmt.Println(piscine.CheckNumber(\"Hello1\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tif piscine.CheckNumber(\"Hello\") {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n\tif piscine.CheckNumber(\"Hello1\") {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"countalpha",
        title:"countalpha",
        style:"function",
        html:"<h2>countalpha</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>CountAlpha()</code> that takes a string as an argument and returns the number of alphabetic characters in the string.</p>\n<h3>Expected functions</h3>\n<pre><code class=\"language-go\">func CountAlpha(s string) int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(CountAlpha(&quot;Hello world&quot;))\n    fmt.Println(CountAlpha(&quot;H e l l o&quot;))\n    fmt.Println(CountAlpha(&quot;H1e2l3l4o&quot;))\n}\n\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n10\n5\n5\n</code></pre>",
        fnFile:"countalpha.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.CountAlpha(\"Hello world\"))\n\tfmt.Println(piscine.CountAlpha(\"H e l l o\"))\n\tfmt.Println(piscine.CountAlpha(\"H1e2l3l4o\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.CountAlpha(\"Hello world\"))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.CountAlpha(\"H e l l o\"))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.CountAlpha(\"H1e2l3l4o\"))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"printif",
        title:"printif",
        style:"function",
        html:"<h2>printif</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes a <code>string</code> as an argument and returns the letter <code>G</code> followed by a newline <code>\\n</code> if the argument length is more or equal than 3, otherwise returns <code>Invalid Input</code> followed by a newline <code>\\n</code>.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func PrintIf(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Print(PrintIf(&quot;abcdefz&quot;))\n    fmt.Print(PrintIf(&quot;14&quot;))\n}\n\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nG$\nInvalid Input$\n</code></pre>",
        fnFile:"printif.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.PrintIf(\"abcdefz\"))\n\tfmt.Print(piscine.PrintIf(\"14\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.PrintIf(\"abcdefz\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.PrintIf(\"14\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"printifnot",
        title:"printifnot",
        style:"function",
        html:"<h2>printifnot</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes a string and returns <code>\"G\\n\"</code> if the string's length is less than 3, <code>\"Invalid Input\\n\"</code> otherwise.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func PrintIfNot(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Print(PrintIfNot(&quot;abcdefz&quot;))\n    fmt.Print(PrintIfNot(&quot;14&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nInvalid Input$\nG$\n</code></pre>",
        fnFile:"printifnot.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.PrintIfNot(\"abcdefz\"))\n\tfmt.Print(piscine.PrintIfNot(\"14\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.PrintIfNot(\"abcdefz\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.PrintIfNot(\"14\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"retainfirsthalf",
        title:"retainfirsthalf",
        style:"function",
        html:"<h2>retainfirsthalf</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>RetainFirstHalf()</code> that takes a <code>string</code> as an argument and returns the first half of this <code>string</code>.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func RetainFirstHalf(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.RetainFirstHalf(&quot;Hello World&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nHello$\n</code></pre>",
        fnFile:"retainfirsthalf.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.RetainFirstHalf(\"Hello World\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.RetainFirstHalf(\"Hello World\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
    ],
  },
  // --- N3 : Strings & maths ---
  {
    id:'n3', name:'N3',
    topic:"Strings & maths",
    tagline:"Words, numbers, and the space between them.",
    exercises:[
      {
        name:"digitlen",
        title:"digitlen",
        style:"function",
        html:"<h2>digitlen</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>DigitLen()</code> that takes two integers as arguments and returns the times the first <code>int</code> can be divided by the second until it reaches zero.</p>\n<ul>\n<li>The second <code>int</code> must be between <strong><em>2</em></strong> and <strong><em>36</em></strong>. If not, the function returns <code>-1</code>.</li>\n<li>If the first <code>int</code> is negative, reverse the sign and count the digits.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func DigitLen(n, base int) int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(DigitLen(100, 10))\n    fmt.Println(DigitLen(100, 2))\n    fmt.Println(DigitLen(-100, 16))\n    fmt.Println(DigitLen(100, -1))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\n3$\n7$\n2$\n-1$\n</code></pre>",
        fnFile:"digitlen.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.DigitLen(100, 10))\n\tfmt.Println(piscine.DigitLen(100, 2))\n\tfmt.Println(piscine.DigitLen(-100, 16))\n\tfmt.Println(piscine.DigitLen(100, -1))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.DigitLen(100, 10))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.DigitLen(100, 2))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.DigitLen(-100, 16))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.DigitLen(100, -1))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"fishandchips",
        title:"fishandchips",
        style:"function",
        html:"<h2>fishandchips</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>FishAndChips()</code> that takes an <code>int</code> and returns a <code>string</code>.</p>\n<ul>\n<li>If the number is divisible by 2, print <code>fish</code>.</li>\n<li>If the number is divisible by 3, print <code>chips</code>.</li>\n<li>If the number is divisible by 2 and 3, print <code>fish and chips</code>.</li>\n<li>If the number is negative return <code>error: number is negative</code>.</li>\n<li>If the number is non divisible by 2 or 3 return <code>error: non divisible</code>.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func FishAndChips(n int) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.FishAndChips(4))\n    fmt.Println(piscine.FishAndChips(9))\n    fmt.Println(piscine.FishAndChips(6))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nfish$\nchips$\nfish and chips$\n</code></pre>",
        fnFile:"fishandchips.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.FishAndChips(4))\n\tfmt.Println(piscine.FishAndChips(9))\n\tfmt.Println(piscine.FishAndChips(6))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.FishAndChips(4) {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.FishAndChips(9) {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.FishAndChips(6) {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"cameltosnakecase",
        title:"cameltosnakecase",
        style:"function",
        html:"<h2>cameltosnakecase</h2>\n<h3>Instructions</h3>\n<p>Write a function that converts a <code>string</code> from <code>camelCase</code> to <code>snake_case</code>.</p>\n<ul>\n<li>If the <code>string</code> is empty, return an empty <code>string</code>.</li>\n<li>If the <code>string</code> is not <code>camelCase</code>, return the <code>string</code> unchanged.</li>\n<li>If the <code>string</code> is <code>camelCase</code>, return the <code>snake_case</code> version of the <code>string</code>.</li>\n</ul>\n<p>For this exercise you need to know that <code>camelCase</code> has two different writing alternatives that will be accepted:</p>\n<ul>\n<li>lowerCamelCase</li>\n<li>UpperCamelCase</li>\n</ul>\n<p>Rules for writing in <code>camelCase</code>:</p>\n<ul>\n<li>The word does not end on a capitalized letter (CamelCasE).</li>\n<li>No two capitalized letters shall follow directly each other (CamelCAse).</li>\n<li>Numbers or punctuation are not allowed in the word anywhere (camelCase1).</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func CamelToSnakeCase(s string) string{\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(CamelToSnakeCase(&quot;HelloWorld&quot;))\n    fmt.Println(CamelToSnakeCase(&quot;helloWorld&quot;))\n    fmt.Println(CamelToSnakeCase(&quot;camelCase&quot;))\n    fmt.Println(CamelToSnakeCase(&quot;CAMELtoSnackCASE&quot;))\n    fmt.Println(CamelToSnakeCase(&quot;camelToSnakeCase&quot;))\n    fmt.Println(CamelToSnakeCase(&quot;hey2&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\nHello_World\nhello_World\ncamel_Case\nCAMELtoSnackCASE\ncamel_To_Snake_Case\nhey2\n</code></pre>",
        fnFile:"cameltosnakecase.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.CamelToSnakeCase(\"HelloWorld\"))\n\tfmt.Println(piscine.CamelToSnakeCase(\"helloWorld\"))\n\tfmt.Println(piscine.CamelToSnakeCase(\"camelCase\"))\n\tfmt.Println(piscine.CamelToSnakeCase(\"CAMELtoSnackCASE\"))\n\tfmt.Println(piscine.CamelToSnakeCase(\"camelToSnakeCase\"))\n\tfmt.Println(piscine.CamelToSnakeCase(\"hey2\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.CamelToSnakeCase(\"HelloWorld\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.CamelToSnakeCase(\"helloWorld\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.CamelToSnakeCase(\"camelCase\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.CamelToSnakeCase(\"CAMELtoSnackCASE\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.CamelToSnakeCase(\"camelToSnakeCase\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.CamelToSnakeCase(\"hey2\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"gcd",
        title:"gcd",
        style:"function",
        html:"<h2>gcd</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes two <code>uint</code> representing two strictly positive integers and returns their greatest common divisor.\nIf any of the input numbers is 0, the function should return 0.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func Gcd(a, b uint) uint {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.Gcd(42, 10))\n    fmt.Println(piscine.Gcd(42, 12))\n    fmt.Println(piscine.Gcd(14, 77))\n    fmt.Println(piscine.Gcd(17, 3))\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\n2\n6\n7\n1\n$\n</code></pre>",
        fnFile:"gcd.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.Gcd(42, 10))\n\tfmt.Println(piscine.Gcd(42, 12))\n\tfmt.Println(piscine.Gcd(14, 77))\n\tfmt.Println(piscine.Gcd(17, 3))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintUint(piscine.Gcd(42, 10))\n\tz01.PrintRune('\\n')\n\tprintUint(piscine.Gcd(42, 12))\n\tz01.PrintRune('\\n')\n\tprintUint(piscine.Gcd(14, 77))\n\tz01.PrintRune('\\n')\n\tprintUint(piscine.Gcd(17, 3))\n\tz01.PrintRune('\\n')\n}\n\nfunc printUint(n uint) {\n\tif n >= 10 {\n\t\tprintUint(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"hashcode",
        title:"hashcode",
        style:"function",
        html:"<h2>hashcode</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>HashCode()</code> that takes a <code>string</code> as an argument and returns a new <strong>hashed</strong> <code>string</code>.</p>\n<ul>\n<li>The hash equation is computed as follows:</li>\n</ul>\n<p><code>(ASCII of current character + size of the string) % 127, ensuring the result falls within the ASCII range of 0 to 127.</code></p>\n<ul>\n<li>If the resulting character is unprintable add <code>33</code> to it.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func HashCode(dec string) string {\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(HashCode(&quot;A&quot;))\n    fmt.Println(HashCode(&quot;AB&quot;))\n    fmt.Println(HashCode(&quot;BAC&quot;))\n    fmt.Println(HashCode(&quot;Hello World&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\nB\nCD\nEDF\nSpwwz+bz}wo\n</code></pre>",
        fnFile:"hashcode.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.HashCode(\"A\"))\n\tfmt.Println(piscine.HashCode(\"AB\"))\n\tfmt.Println(piscine.HashCode(\"BAC\"))\n\tfmt.Println(piscine.HashCode(\"Hello World\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.HashCode(\"A\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.HashCode(\"AB\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.HashCode(\"BAC\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n\tfor _, r := range piscine.HashCode(\"Hello World\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"lastword",
        title:"lastword",
        style:"function",
        html:"<h2>lastword</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>LastWord</code> that takes a <code>string</code> and returns its last word followed by a <code>\\n</code>.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func LastWord(s string) string{\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Print(piscine.LastWord(&quot;this        ...       is sparta, then again, maybe    not&quot;))\n    fmt.Print(piscine.LastWord(&quot; lorem,ipsum &quot;))\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nnot$\nlorem,ipsum$\n$\n</code></pre>",
        fnFile:"lastword.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.LastWord(\"this        ...       is sparta, then again, maybe    not\"))\n\tfmt.Print(piscine.LastWord(\" lorem,ipsum \"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.LastWord(\"this        ...       is sparta, then again, maybe    not\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.LastWord(\" lorem,ipsum \") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"firstword",
        title:"firstword",
        style:"function",
        html:"<h2>firstword</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes a string and return a string containing its first word, followed by a newline (<code>'\\n'</code>).</p>\n<ul>\n<li>A word is a sequence of characters delimited by spaces or by the start/end of the argument.</li>\n</ul>\n<h3>Expected Function</h3>\n<pre><code class=\"language-go\">func FirstWord(s string) string {\n    // ...\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible way to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Print(piscine.FirstWord(&quot;hello there&quot;))\n    fmt.Print(piscine.FirstWord(&quot;&quot;))\n    fmt.Print(piscine.FirstWord(&quot;hello   .........  bye&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\nhello\n\nhello\n$\n</code></pre>",
        fnFile:"firstword.go",
        stub:"",
        mainCode:"package main\n\nimport (\n    \"fmt\"\n\n    \"piscine\"\n)\n\nfunc main() {\n    fmt.Print(piscine.FirstWord(\"hello there\"))\n    fmt.Print(piscine.FirstWord(\"\"))\n    fmt.Print(piscine.FirstWord(\"hello   .........  bye\"))\n}\n",
        piscineMain:"package main\n\nimport (\n    \"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n    for _, r := range piscine.FirstWord(\"hello there\") {\n    \tz01.PrintRune(r)\n    }\n    for _, r := range piscine.FirstWord(\"\") {\n    \tz01.PrintRune(r)\n    }\n    for _, r := range piscine.FirstWord(\"hello   .........  bye\") {\n    \tz01.PrintRune(r)\n    }\n}\n",
      },
      {
        name:"repeatalpha",
        title:"repeatalpha",
        style:"function",
        html:"<h2>repeatalpha</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>RepeatAlpha</code> that takes a <code>string</code> and displays it repeating each alphabetical character as many times as its alphabetical index.</p>\n<h3>Expected Function</h3>\n<pre><code class=\"language-go\">func RepeatAlpha(s string) string {\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.RepeatAlpha(&quot;abc&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nabbccc$\n</code></pre>",
        fnFile:"repeatalpha.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.RepeatAlpha(\"abc\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.RepeatAlpha(\"abc\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"searchreplace",
        title:"searchreplace",
        style:"program",
        html:"<h2>searchreplace</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes 3 arguments, the first argument is a <code>string</code> in which a letter (the 2nd argument) will be replaced by another one (the 3rd argument).</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;hella there&quot; &quot;a&quot; &quot;o&quot;\nhello there\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
  // --- N4 : Structures & primes ---
  {
    id:'n4', name:'N4',
    topic:"Structures & primes",
    tagline:"Arrays, memory, primes — it gets real.",
    exercises:[
      {
        name:"findprevprime",
        title:"findprevprime",
        style:"function",
        html:"<h2>findprevprime</h2>\n<h3>Instructions</h3>\n<p>Write a function that returns the first prime number that is equal or inferior to the <code>int</code> passed as parameter.</p>\n<p>If there are no primes inferior to the <code>int</code> passed as parameter the function should return 0.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func FindPrevPrime(nb int) int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nimport &quot;fmt&quot;\n\nfunc main() {\n    fmt.Println(FindPrevPrime(5))\n    fmt.Println(FindPrevPrime(4))\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\n5\n3\n$\n</code></pre>",
        fnFile:"findprevprime.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.FindPrevPrime(5))\n\tfmt.Println(piscine.FindPrevPrime(4))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.FindPrevPrime(5))\n\tz01.PrintRune('\\n')\n\tprintInt(piscine.FindPrevPrime(4))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"thirdtimeisacharm",
        title:"thirdtimeisacharm",
        style:"function",
        html:"<h2>thirdtimeisacharm</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>ThirdTimeIsACharm()</code> that takes a <code>string</code> as an argument and returns another <code>string</code> with every third character.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func ThirdTimeIsACharm(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Print(ThirdTimeIsACharm(&quot;123456789&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\n369$\n</code></pre>",
        fnFile:"thirdtimeisacharm.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.ThirdTimeIsACharm(\"123456789\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.ThirdTimeIsACharm(\"123456789\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"printrevcomb",
        title:"printrevcomb",
        style:"program",
        html:"<h2>printrevcomb</h2>\n<h3>Instructions</h3>\n<p>Write a program that prints in descending order on a single line all unique combinations of three different digits so that the first digit is greater than the second and the second is greater than the third.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . | cat -e\n987, 986, 985, ..., 310, 210$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"printmemory",
        title:"printmemory",
        style:"function",
        html:"<h2>printmemory</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes <code>(arr [10]byte)</code>, and displays the memory as in the example.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func PrintMemory(arr [10]byte) {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nimport &quot;piscine&quot;\n\nfunc main() {\n    piscine.PrintMemory([10]byte{'h', 'e', 'l', 'l', 'o', 16, 21, '*'})\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\n68 65 6c 6c$\n6f 10 15 2a$\n00 00$\nhello..*..$\n$\n</code></pre>",
        fnFile:"printmemory.go",
        stub:"",
        mainCode:"package main\n\nimport \"piscine\"\n\nfunc main() {\n\tpiscine.PrintMemory([10]byte{'h', 'e', 'l', 'l', 'o', 16, 21, '*'})\n}\n",
        piscineMain:null,
      },
      {
        name:"weareunique",
        title:"weareunique",
        style:"function",
        html:"<h2>weareunique</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes two <code>strings</code>'s and returns the number of characters that are not included in both, without repeating characters.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func WeAreUnique(str1 , str2 string) int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(WeAreUnique(&quot;foo&quot;, &quot;boo&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n2\n</code></pre>",
        fnFile:"weareunique.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.WeAreUnique(\"foo\", \"boo\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tprintInt(piscine.WeAreUnique(\"foo\", \"boo\"))\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"itoa",
        title:"itoa",
        style:"function",
        html:"<h2>itoa</h2>\n<h3>Instructions</h3>\n<p>Write a function that simulates the behavior of the <code>Itoa</code> function in Go.</p>\n<h2>Expected function</h2>\n<pre><code class=\"language-go\">func Itoa(n int) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.Itoa(12345))\n    fmt.Println(piscine.Itoa(0))\n    fmt.Println(piscine.Itoa(-1234))\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\n12345\n0\n-1234\n$\n</code></pre>",
        fnFile:"itoa.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n    fmt.Println(piscine.Itoa(12345))\n    fmt.Println(piscine.Itoa(0))\n    fmt.Println(piscine.Itoa(-1234))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n    for _, r := range piscine.Itoa(12345) {\n    \tz01.PrintRune(r)\n    }\n    z01.PrintRune('\\n')\n    for _, r := range piscine.Itoa(0) {\n    \tz01.PrintRune(r)\n    }\n    z01.PrintRune('\\n')\n    for _, r := range piscine.Itoa(-1234) {\n    \tz01.PrintRune(r)\n    }\n    z01.PrintRune('\\n')\n}\n",
      },
      {
        name:"iscapitalized",
        title:"iscapitalized",
        style:"function",
        html:"<h2>iscapitalized</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>IsCapitalized()</code> that takes a <code>string</code> as an argument and returns <code>true</code> if each word in the <code>string</code> begins with either an uppercase letter or a non-alphabetic character.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func IsCapitalized(s string) bool {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(IsCapitalized(&quot;Hello! How are you?&quot;))\n    fmt.Println(IsCapitalized(&quot;Hello How Are You&quot;))\n    fmt.Println(IsCapitalized(&quot;&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\nfalse\ntrue\nfalse\n</code></pre>",
        fnFile:"iscapitalized.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.IsCapitalized(\"Hello! How are you?\"))\n\tfmt.Println(piscine.IsCapitalized(\"Hello How Are You\"))\n\tfmt.Println(piscine.IsCapitalized(\"\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tif piscine.IsCapitalized(\"Hello! How are you?\") {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n\tif piscine.IsCapitalized(\"Hello How Are You\") {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n\tif piscine.IsCapitalized(\"\") {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"fromto",
        title:"fromto",
        style:"function",
        html:"<h2>fromto</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes two <code>integers</code> and returns a <code>string</code> showing the range of numbers from the first to the second.</p>\n<ul>\n<li>The numbers must be separated by a comma and a space.</li>\n<li>If any of the arguments is bigger than <code>99</code> or less than <code>0</code>, the function returns <code>Invalid</code> followed by a newline <code>\\n</code>.</li>\n<li>Prepend a <code>0</code> to any number that is less than <code>10</code>.</li>\n<li>Add a new line <code>\\n</code> at the end of the <code>string</code>.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func FromTo(from int, to int) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Print(piscine.FromTo(1, 10))\n    fmt.Print(piscine.FromTo(10, 1))\n    fmt.Print(piscine.FromTo(10, 10))\n    fmt.Print(piscine.FromTo(100, 10))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\n01, 02, 03, 04, 05, 06, 07, 08, 09, 10$\n10, 09, 08, 07, 06, 05, 04, 03, 02, 01$\n10$\nInvalid$\n</code></pre>",
        fnFile:"fromto.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.FromTo(1, 10))\n\tfmt.Print(piscine.FromTo(10, 1))\n\tfmt.Print(piscine.FromTo(10, 10))\n\tfmt.Print(piscine.FromTo(100, 10))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.FromTo(1, 10) {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.FromTo(10, 1) {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.FromTo(10, 10) {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.FromTo(100, 10) {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"zipstring",
        title:"zipstring",
        style:"function",
        html:"<h2>zipstring</h2>\n<h3>Instructions</h3>\n<p>Write a function that takes a <code>string</code> and returns a new <code>string</code> that replaces every character with the number of duplicates and the character itself.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func ZipString(s string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(ZipString(&quot;YouuungFellllas&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n1Y1o3u1n1g1F1e4l1a1s\n</code></pre>",
        fnFile:"zipstring.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.ZipString(\"YouuungFellllas\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.ZipString(\"YouuungFellllas\") {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"expandstr",
        title:"expandstr",
        style:"program",
        html:"<h2>expandstr</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a <code>string</code> and displays it with exactly three spaces between each word, with no spaces nor tabs at neither the beginning nor the end.</p>\n<p>The <code>string</code> will be followed by a newline (<code>'\\n'</code>).</p>\n<p>A word, in this exercise, is a sequence of visible characters.</p>\n<p>If the number of arguments is not 1, or if there are no word, the program displays nothing.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;you   see   it's   easy   to   display   the   same   thing&quot; | cat -e\nyou   see   it's   easy   to   display   the   same   thing$\n$ go run . &quot;   only  it's harder   &quot; | cat -e\nonly   it's   harder$\n$ go run . &quot; how funny it is&quot; &quot;did you  hear, Mathilde ?&quot; | cat -e\n$ go run .\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"cleanstr",
        title:"cleanstr",
        style:"program",
        html:"<h2>cleanstr</h2>\n<h3>Instructions</h3>\n<p>Write a <strong>program</strong> that takes a <code>string</code>, and displays this <code>string</code> with exactly:</p>\n<ul>\n<li>one space between words.</li>\n<li>without spaces nor tabs at the beginning nor at the end.</li>\n<li>with the result followed by a newline (\"<code>\\n</code>\").</li>\n</ul>\n<p>A \"word\" is defined as a part of a <code>string</code> delimited either by spaces/tabs, or\nby the start/end of the <code>string</code>.</p>\n<p>If the number of arguments is not 1, or if there are no words to display, the\nprogram displays a newline(\"<code>\\n</code>\").</p>\n<h3>Usage :</h3>\n<pre><code class=\"language-console\">$ go run . &quot;you see it's easy to display the same thing&quot; | cat -e\nyou see it's easy to display the same thing$\n$ go run . &quot; only    it's  harder   &quot;\nonly it's harder$\n$ go run . &quot; how funny&quot; &quot;Did you   hear Mathilde ?&quot;\n\n$ go run . &quot;&quot;\n\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
  // --- N5 : Slices & recursion ---
  {
    id:'n5', name:'N5',
    topic:"Slices & recursion",
    tagline:"Slices, unions, primes, jumps.",
    exercises:[
      {
        name:"concatalternate",
        title:"concatalternate",
        style:"function",
        html:"<h2>concatalternate</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>ConcatAlternate()</code> that receives two slices of an <code>int</code> as arguments and returns a new slice with the result of the alternated values of each slice.</p>\n<ul>\n<li>The input slices can be of different lengths.</li>\n<li>The new slice should start with an element of the largest slice.</li>\n<li>If the slices are of equal length, the new slice should return the elements of the first slice first and then the elements of the second slice.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func ConcatAlternate(slice1,slice2 []int) []int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))\n    fmt.Println(ConcatAlternate([]int{2, 4, 6, 8, 10}, []int{1, 3, 5, 7, 9, 11}))\n    fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6, 7, 8, 9}))\n    fmt.Println(ConcatAlternate([]int{1, 2, 3}, []int{}))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n[1 4 2 5 3 6]\n[1 2 3 4 5 6 7 8 9 10 11]\n[4 1 5 2 6 3 7 8 9]\n[1 2 3]\n</code></pre>",
        fnFile:"concatalternate.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))\n\tfmt.Println(piscine.ConcatAlternate([]int{2, 4, 6, 8, 10}, []int{1, 3, 5, 7, 9, 11}))\n\tfmt.Println(piscine.ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6, 7, 8, 9}))\n\tfmt.Println(piscine.ConcatAlternate([]int{1, 2, 3}, []int{}))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatAlternate([]int{2, 4, 6, 8, 10}, []int{1, 3, 5, 7, 9, 11}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6, 7, 8, 9}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatAlternate([]int{1, 2, 3}, []int{}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"reversestrcap",
        title:"reversestrcap",
        style:"program",
        html:"<h2>reversestrcap</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes one or more arguments and that, for each argument, puts the last letter of each word in uppercase and the rest in lowercase.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;First SMALL TesT&quot; | cat -e\nfirsT smalL tesT$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"wdmatch",
        title:"wdmatch",
        style:"program",
        html:"<h2>wdmatch</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes two <code>string</code> and checks whether it is possible to write the first <code>string</code> with characters from the second <code>string</code>.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . 123 123\n123\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"hiddenp",
        title:"hiddenp",
        style:"program",
        html:"<h2>hiddenp</h2>\n<h3>Instructions</h3>\n<p>Write a program named <code>hiddenp</code> that takes two <code>strings</code> as arguments and checks if s1 is hidden in s2.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;abc&quot; &quot;2altrb53c.sse&quot; | cat -e\n1$\n$ go run . &quot;abc&quot; &quot;btarc&quot; | cat -e\n0$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"concatslice",
        title:"concatslice",
        style:"function",
        html:"<h2>concatslice</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>ConcatSlice()</code> that takes two slices of integers as arguments and returns the concatenation of the two slices.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func ConcatSlice(slice1, slice2 []int) []int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.ConcatSlice([]int{1, 2, 3}, []int{4, 5, 6}))\n    fmt.Println(piscine.ConcatSlice([]int{}, []int{4, 5, 6, 7, 8, 9}))\n    fmt.Println(piscine.ConcatSlice([]int{1, 2, 3}, []int{}))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n[1 2 3 4 5 6]\n[4 5 6 7 8 9]\n[1 2 3]\n</code></pre>",
        fnFile:"concatslice.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.ConcatSlice([]int{1, 2, 3}, []int{4, 5, 6}))\n\tfmt.Println(piscine.ConcatSlice([]int{}, []int{4, 5, 6, 7, 8, 9}))\n\tfmt.Println(piscine.ConcatSlice([]int{1, 2, 3}, []int{}))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatSlice([]int{1, 2, 3}, []int{4, 5, 6}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatSlice([]int{}, []int{4, 5, 6, 7, 8, 9}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.ConcatSlice([]int{1, 2, 3}, []int{}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
      {
        name:"inter",
        title:"inter",
        style:"program",
        html:"<h2>inter</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes two <code>string</code> and displays, without doubles, the characters that appear in both <code>string</code>, in the order they appear in the first one.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;padinton&quot; &quot;paqefwtdjetyiytjneytjoeyjnejeyj&quot;\npadinto\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"union",
        title:"union",
        style:"program",
        html:"<h2>union</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes two <code>string</code> and displays, without doubles, the characters that appear in either one of the <code>string</code>.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . zpadinton paqefwtdjetyiytjneytjoeyjnejeyj | cat -e\nzpadintoqefwjy$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"saveandmiss",
        title:"saveandmiss",
        style:"function",
        html:"<h2>saveandmiss</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>SaveAndMiss()</code> that takes a <code>string</code> and an <code>int</code> as an argument.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func SaveAndMiss(arg string, num int) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.SaveAndMiss(&quot;123456789&quot;, 3))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\n123789$\n</code></pre>",
        fnFile:"saveandmiss.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.SaveAndMiss(\"123456789\", 3))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.SaveAndMiss(\"123456789\", 3) {\n\t\tz01.PrintRune(r)\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
      {
        name:"chunk",
        title:"chunk",
        style:"function",
        html:"<h2>chunk</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>Chunk</code> that receives as parameters a slice, <code>slice []int</code>, and a number <code>size int</code>. The goal of this function is to chunk a slice into many sub slices where each sub slice has the length of <code>size</code>.</p>\n<ul>\n<li>If the <code>size</code> is <code>0</code> it should print a newline (<code>'\\n'</code>).</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func Chunk(slice []int, size int) {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nfunc main() {\n    Chunk([]int{}, 10)\n    Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 0)\n    Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 3)\n    Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 5)\n    Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 4)\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\n[]\n\n[[0 1 2] [3 4 5] [6 7]]\n[[0 1 2 3 4] [5 6 7]]\n[[0 1 2 3] [4 5 6 7]]\n$\n</code></pre>",
        fnFile:"chunk.go",
        stub:"",
        mainCode:"package main\n\nimport \"piscine\"\n\nfunc main() {\n\tpiscine.Chunk([]int{}, 10)\n\tpiscine.Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 0)\n\tpiscine.Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 3)\n\tpiscine.Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 5)\n\tpiscine.Chunk([]int{0, 1, 2, 3, 4, 5, 6, 7}, 4)\n}\n",
        piscineMain:null,
      },
      {
        name:"addprimesum",
        title:"addprimesum",
        style:"program",
        html:"<h2>addprimesum</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a positive integer as argument and displays the sum of all prime numbers inferior or equal to it followed by a newline (<code>'\\n'</code>).</p>\n<ul>\n<li>If the number of arguments is different from 1, or if the argument is not a positive number, the program displays <code>0</code> followed by a newline.</li>\n</ul>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . 5\n10\n$ go run . 7\n17\n$ go run . -2\n0\n$ go run . 0\n0\n$ go run .\n0\n$ go run . 5 7\n0\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"fprime",
        title:"fprime",
        style:"program",
        html:"<h2>fprime</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a positive <code>int</code> and displays its prime factors, followed by a newline (<code>'\\n'</code>).</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . 225225\n3*3*5*5*7*11*13\n$ go run . 42\n2*3*7\n$ go run . a\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"canjump",
        title:"canjump",
        style:"function",
        html:"<h2>Can Jump</h2>\n<p>Given an array of non-negative integers representing the number of steps you can take forward from each position, implement the function <code>CanJump()</code> which takes a slice of unsigned integers <code>[]uint</code> as input and returns a <code>boolean</code> value. This function should determine if it's possible to reach and stay at the last index of the array starting from the first index, based on the steps you need to advance. Be aware that:</p>\n<ul>\n<li>Each value represents the exact number of steps you must take forward from that position.</li>\n<li>The function should return <code>true</code> if it's possible to reach and stay at the last index without stepping out of the array, and <code>false</code> otherwise.</li>\n<li>If the input has only one element, that is the last position in the array so the function will return <code>true</code> but if the array is empty it returns <code>false</code>.</li>\n</ul>\n<p>Let's take the example array input := []uint{2, 3, 1, 1, 4}.</p>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    input1 := []uint{2, 3, 1, 1, 4}\n    fmt.Println(piscine.CanJump(input1))\n\n    input2 := []uint{3, 2, 1, 0, 4}\n    fmt.Println(piscine.CanJump(input2))\n\n    input3 := []uint{0}\n    fmt.Println(piscine.CanJump(input3))\n}\n</code></pre>\n<p>And its output :</p>\n<pre><code class=\"language-console\">$ go run .\ntrue\nfalse\ntrue\n$\n</code></pre>",
        fnFile:"canjump.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tinput1 := []uint{2, 3, 1, 1, 4}\n\tfmt.Println(piscine.CanJump(input1))\n\n\tinput2 := []uint{3, 2, 1, 0, 4}\n\tfmt.Println(piscine.CanJump(input2))\n\n\tinput3 := []uint{0}\n\tfmt.Println(piscine.CanJump(input3))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tinput1 := []uint{2, 3, 1, 1, 4}\n\tif piscine.CanJump(input1) {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n\tinput2 := []uint{3, 2, 1, 0, 4}\n\tif piscine.CanJump(input2) {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n\tinput3 := []uint{0}\n\tif piscine.CanJump(input3) {\n\t\tz01.PrintRune('T')\n\t} else {\n\t\tz01.PrintRune('F')\n\t}\n\tz01.PrintRune('\\n')\n}\n",
      },
    ],
  },
  // --- N6 : Découpe & tri ---
  {
    id:'n6', name:'N6',
    topic:"Découpe & tri",
    tagline:"Cutting, slicing, skipping.",
    exercises:[
      {
        name:"notdecimal",
        title:"notdecimal",
        style:"function",
        html:"<h2>notdecimal</h2>\n<h3>Instructions</h3>\n<p>Write a function called <code>NotDecimal()</code> that takes as an argument a <code>string</code> in form of a float number with the decimal point and returns a string converted to <code>int</code> without the decimal point.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func NotDecimal(dec string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n)\n\nfunc main() {\n    fmt.Print(NotDecimal(&quot;0.1&quot;))\n    fmt.Print(NotDecimal(&quot;174.2&quot;))\n    fmt.Print(NotDecimal(&quot;1952&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .  | cat -e\n1$\n1742$\n1952$\n</code></pre>",
        fnFile:"notdecimal.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.NotDecimal(\"0.1\"))\n\tfmt.Print(piscine.NotDecimal(\"174.2\"))\n\tfmt.Print(piscine.NotDecimal(\"1952\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.NotDecimal(\"0.1\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.NotDecimal(\"174.2\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.NotDecimal(\"1952\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"slice",
        title:"slice",
        style:"function",
        html:"<h2>slice</h2>\n<h3>Instructions</h3>\n<p>The function receives a slice of strings and one or more integers, and returns a slice of strings.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func Slice(a []string, nbrs... int) []string{\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function :</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main(){\n    a := []string{&quot;coding&quot;, &quot;algorithm&quot;, &quot;ascii&quot;, &quot;package&quot;, &quot;golang&quot;}\n    fmt.Printf(&quot;%#v\\n&quot;, piscine.Slice(a, 1))\n}\n</code></pre>\n<pre><code class=\"language-console\">$ go run .\n[]string{&quot;algorithm&quot;, &quot;ascii&quot;, &quot;package&quot;, &quot;golang&quot;}\n</code></pre>",
        fnFile:"slice.go",
        stub:"",
        mainCode:"package main\n\nimport (\n    \"fmt\"\n    \"piscine\"\n)\n\nfunc main(){\n    a := []string{\"coding\", \"algorithm\", \"ascii\", \"package\", \"golang\"}\n    fmt.Printf(\"%#v\\n\", piscine.Slice(a, 1))\n}\n",
        piscineMain:"package main\n\nimport (\n    \"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main(){\n    a := []string{\"coding\", \"algorithm\", \"ascii\", \"package\", \"golang\"}\n    z01.PrintRune('[')\n    for i, v := range piscine.Slice(a, 1) {\n    \tif i > 0 { z01.PrintRune(' ') }\n    \tfor _, r := range v { z01.PrintRune(r) }\n    }\n    z01.PrintRune(']')\n    z01.PrintRune('\\n')\n}\n",
      },
      {
        name:"fifthandskip",
        title:"fifthandskip",
        style:"function",
        html:"<h2>fifthandskip</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>FifthAndSkip()</code> that takes a <code>string</code> and returns another <code>string</code>. The function separates every five characters of the <code>string</code> with a space and removes the sixth one.</p>\n<ul>\n<li>If there are spaces in the middle of a word, ignore them and get the first character after the spaces until you reach a length of 5.</li>\n<li>If the <code>string</code> is less than 5 characters return <code>Invalid Input</code> followed by a newline <code>\\n</code>.</li>\n<li>If the <code>string</code> is empty return a newline <code>\\n</code>.</li>\n</ul>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func FifthAndSkip(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Print(piscine.FifthAndSkip(&quot;abcdefghijklmnopqrstuwxyz&quot;))\n    fmt.Print(piscine.FifthAndSkip(&quot;This is a short sentence&quot;))\n    fmt.Print(piscine.FifthAndSkip(&quot;1234&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nabcde ghijk mnopq stuwx z$\nThisi ashor sente ce$\nInvalid Input$\n</code></pre>",
        fnFile:"fifthandskip.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.FifthAndSkip(\"abcdefghijklmnopqrstuwxyz\"))\n\tfmt.Print(piscine.FifthAndSkip(\"This is a short sentence\"))\n\tfmt.Print(piscine.FifthAndSkip(\"1234\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.FifthAndSkip(\"abcdefghijklmnopqrstuwxyz\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.FifthAndSkip(\"This is a short sentence\") {\n\t\tz01.PrintRune(r)\n\t}\n\tfor _, r := range piscine.FifthAndSkip(\"1234\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"revconcatalternate",
        title:"revconcatalternate",
        style:"function",
        html:"<h2>revconcatalternate</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>RevConcatAlternate()</code> that receives two slices of <code>int</code> as arguments and returns a new slice with alternated values of each slice in reverse order.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func RevConcatAlternate(slice1,slice2 []int) []int {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Println(piscine.RevConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run .\n[3 6 2 5 1 4]\n</code></pre>",
        fnFile:"revconcatalternate.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.RevConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tz01.PrintRune('[')\n\tfor i, v := range piscine.RevConcatAlternate([]int{1, 2, 3}, []int{4, 5, 6}) {\n\t\tif i > 0 { z01.PrintRune(' ') }\n\t\tprintInt(v)\n\t}\n\tz01.PrintRune(']')\n\tz01.PrintRune('\\n')\n}\n\nfunc printInt(n int) {\n\tif n < 0 {\n\t\tz01.PrintRune('-')\n\t\tn = -n\n\t}\n\tif n >= 10 {\n\t\tprintInt(n / 10)\n\t}\n\tz01.PrintRune(rune('0' + n%10))\n}\n",
      },
    ],
  },
  // --- N7 : Mots & paires ---
  {
    id:'n7', name:'N7',
    topic:"Mots & paires",
    tagline:"Flip it, reverse it, rotate it.",
    exercises:[
      {
        name:"wordflip",
        title:"wordflip",
        style:"function",
        html:"<h2>wordflip</h2>\n<h3>Instructions</h3>\n<p>Write a function <code>WordFlip()</code> that takes a <code>string</code> as input and returns it in reverse order.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func WordFlip(str string) string {\n\n}\n</code></pre>\n<h3>Usage</h3>\n<p>Here is a possible program to test your function:</p>\n<pre><code class=\"language-go\">package main\n\nimport (\n    &quot;fmt&quot;\n    &quot;piscine&quot;\n)\n\nfunc main() {\n    fmt.Print(piscine.WordFlip(&quot;First second last&quot;))\n}\n</code></pre>\n<p>And its output:</p>\n<pre><code class=\"language-console\">$ go run . | cat -e\nlast second First$\n</code></pre>",
        fnFile:"wordflip.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Print(piscine.WordFlip(\"First second last\"))\n}\n",
        piscineMain:"package main\n\nimport (\n\t\"piscine\"\n\t\"github.com/01-edu/z01\"\n)\n\nfunc main() {\n\tfor _, r := range piscine.WordFlip(\"First second last\") {\n\t\tz01.PrintRune(r)\n\t}\n}\n",
      },
      {
        name:"revwstr",
        title:"revwstr",
        style:"program",
        html:"<h2>revwstr</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a <code>string</code> as a parameter, and prints its words in reverse, followed by a newline.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;the time of contempt precedes that of indifference&quot;\nindifference of that precedes contempt of time the\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"rostring",
        title:"rostring",
        style:"program",
        html:"<h2>rostring</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a <code>string</code> and displays this <code>string</code> after rotating it one word to the left.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;Let there     be light&quot;\nthere be light Let\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"findpairs",
        title:"findpairs",
        style:"program",
        html:"<h2>Find Pairs</h2>\n<h3>Instructions</h3>\n<p>Write a program that finds all pairs of elements in an integer array that sum up to a given target value.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;[1, 2, 3, 4, 5]&quot; &quot;6&quot;\nPairs with sum 6: [[0 4] [1 3]]\n$ go run . &quot;[-1, 2, -3, 4, -5]&quot; &quot;1&quot;\nPairs with sum 1: [[0 1] [2 3]]\n$ go run . &quot;[1, 2, 3, 4, 5]&quot; &quot;10&quot;\nNo pairs found.\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
  // --- N8 : Bits & latin ---
  {
    id:'n8', name:'N8',
    topic:"Bits & latin",
    tagline:"Options, romans, pig latin.",
    exercises:[
      {
        name:"options",
        title:"options",
        style:"program",
        html:"<h1>options</h1>\n<h2>Instructions</h2>\n<p>Write a program that takes an undefined number of arguments which could be considered as <code>options</code>.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . -abc -ijk | cat -e\n00000000 00000000 00000111 00000111$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"romannumbers",
        title:"romannumbers",
        style:"program",
        html:"<h2>romannumbers</h2>\n<h3>Instructions</h3>\n<p>Write a program called <code>rn</code>. The objective is to convert a number, given as an argument, into a roman number and print it with its roman number calculation.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . 123\nC+X+X+I+I+I\nCXXIII\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"piglatin",
        title:"piglatin",
        style:"program",
        html:"<h2>piglatin</h2>\n<h3>Instructions</h3>\n<p>Write a <strong>program</strong> that transforms a string passed as argument in its <code>Pig Latin</code> version.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . pig | cat -e\nigpay$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"itoabase",
        title:"itoabase",
        style:"function",
        html:"<h2>itoabase</h2>\n<h3>Instructions</h3>\n<p>Write a function that converts an <code>int</code> value to a <code>string</code> using the specified base in the argument.</p>\n<h3>Expected function</h3>\n<pre><code class=\"language-go\">func ItoaBase(value, base int) string {\n\n}\n</code></pre>",
        fnFile:"itoabase.go",
        stub:"",
        mainCode:"package main\n\nimport (\n\t\"fmt\"\n\t\"piscine\"\n)\n\nfunc main() {\n\tfmt.Println(piscine.ItoaBase(255, 16))\n\tfmt.Println(piscine.ItoaBase(-10, 2))\n}\n",
        piscineMain:null,
      },
    ],
  },
  // --- N9 : Piles & calcul ---
  {
    id:'n9', name:'N9',
    topic:"Piles & calcul",
    tagline:"Stacks and reverse polish notation.",
    exercises:[
      {
        name:"rpncalc",
        title:"rpncalc",
        style:"program",
        html:"<h2>rpncalc</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes a <code>string</code> which contains an equation written in <code>Reverse Polish Notation</code> (RPN) as its first argument, that evaluates the equation.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;1 2 * 3 * 4 +&quot; | cat -e\n10$\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"brackets",
        title:"brackets",
        style:"program",
        html:"<h2>brackets</h2>\n<h3>Instructions</h3>\n<p>Write a program that takes an undefined number of <code>string</code> in arguments. For each argument, if the expression is correctly bracketed, the program prints on the standard output <code>OK</code> followed by a newline (<code>'\\n'</code>), otherwise it prints <code>Error</code> followed by a newline.</p>\n<p>Symbols considered as brackets are parentheses <code>(</code> and <code>)</code>, square brackets <code>[</code> and <code>]</code> and curly braces <code>{</code> and <code>}</code>. Every other symbols are simply ignored.</p>\n<p>An opening bracket must always be closed by the good closing bracket in the correct order. A <code>string</code> which does not contain any bracket is considered as a correctly bracketed <code>string</code>.</p>\n<p>If there is no argument, the program must print nothing.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . '(johndoe)' | cat -e\nOK$\n$ go run . '([)]' | cat -e\nError$\n$ go run . '' '{[(0 + 0)(1 + 1)](3*(-1)){()}}' | cat -e\nOK$\nOK$\n$ go run .\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
  // --- N10 : Le grand saut ---
  {
    id:'n10', name:'N10',
    topic:"Le grand saut",
    tagline:"Brainfuck and regex-like grouping. The final stretch.",
    exercises:[
      {
        name:"brainfuck",
        title:"brainfuck",
        style:"program",
        html:"<h2>brainfuck</h2>\n<blockquote>\n<p>Esoteric programming languages (esolang) are designed to test the boundaries of computer programming design, as proofs of concept, as software art, as a hacking interface or simply as a joke. One such esoteric language is <code>Brainfuck</code>. It was created by Urban Müller in 1993. It is a minimalist language consisting of 8 simple commands. It is Turing complete, but is not intended for practical use. It exists to amuse and challenge programmers.</p>\n</blockquote>\n<h3>Instructions</h3>\n<p>Write a <code>Brainfuck</code> interpreter program.</p>\n<p>The source code will be given as the first parameter, and will always be valid with fewer than 4096 operations.</p>\n<p>Your <code>Brainfuck</code> interpreter will consist of an array of 2048 bytes, all initialized to 0, with a pointer to the first byte.</p>\n<p>Every operator consists of a single character:</p>\n<ul>\n<li><code>&gt;</code>: increment the pointer.</li>\n<li><code>&lt;</code>: decrement the pointer.</li>\n<li><code>+</code>: increment the pointed byte.</li>\n<li><code>-</code>: decrement the pointed byte.</li>\n<li><code>.</code>: print the pointed byte to standard output.</li>\n<li><code>[</code>: If the byte at the current pointer is 0, skip forward to the command after the matching <code>]</code>.</li>\n<li><code>]</code>: If the byte at the current pointer is not 0, jump back to the command after the matching <code>[</code>.</li>\n<li>Any other character is treated as a comment and ignored.</li>\n</ul>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;++++++++++[&gt;+++++++&gt;++++++++++&gt;+++&gt;+&lt;&lt;&lt;&lt;-]&gt;++.&gt;+.+++++++..+++.&gt;++.&lt;&lt;+++++++++++++++.&gt;.+++.------.--------.&gt;+.&gt;.&quot; | cat -e\nHello World!$\n$ go run . &quot;+++++[&gt;++++[&gt;++++H&gt;+++++i&lt;&lt;-]&gt;&gt;&gt;++\\n&lt;&lt;&lt;&lt;-]&gt;&gt;--------.&gt;+++++.&gt;.&quot; | cat -e\nHi$\n$ go run . &quot;++++++++++[&gt;++++++++++&gt;++++++++++&gt;++++++++++&lt;&lt;&lt;-]&gt;---.&gt;--.&gt;-.&gt;++++++++++.&quot; | cat -e\nabc$\n$ go run .\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
      {
        name:"grouping",
        title:"grouping",
        style:"program",
        html:"<h2>grouping</h2>\n<h3>Instructions</h3>\n<p>Write a program that receives two strings and replicates the use of brackets in regular expressions.</p>\n<h3>Usage</h3>\n<pre><code class=\"language-console\">$ go run . &quot;(a)&quot; &quot;I'm heavy, jumpsuit is on steady&quot;\n1: heavy\n2: steady\n$\n</code></pre>",
        fnFile:"main.go",
        stub:"",
        mainCode:null,
        piscineMain:null,
      },
    ],
  },
];